apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react
  labels:
    app: react
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: ft-tls
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react
                port:
                  number: 80
